"""logger.py — Interaction logging for the RAG pipeline.

WHY THIS FILE EXISTS:
    Every query, its type, similarity scores, and response length are recorded
    here for later analysis. Keeping logging separate from the pipeline means
    you can change what gets logged without touching retrieval logic.

TWO LEVELS OF LOGGING:
    1. Python's built-in logging module  — for errors, warnings, and debug info.
       These go to the terminal (or log collector in production).
    2. JSON file logger (log_interaction) — for structured query analytics.
       These go to rag_logs.json for data analysis.
"""

import json
import logging
import os
from datetime import datetime
from typing import List

from src.rag.config import LOG_FILE

__all__ = ['log_interaction']

# Module-level logger — use this for errors and warnings in this module
logger = logging.getLogger(__name__)


def log_interaction(
    query: str,
    qtype: str,
    chunks_used: int,
    sim_scores: list,
    response: str,
) -> None:
    """Append one query interaction to the JSON log file.

    Logs are used for analytics — tracking similarity score trends, query type
    distribution, and response length over time.

    Args:
        query:       The user's question exactly as typed.
        qtype:       Query classification: 'factual', 'comparison', 'general', or 'summarise'.
        chunks_used: Number of chunks that were passed to the LLM.
        sim_scores:  List of cosine similarity scores for the retrieved chunks.
        response:    The final answer text generated by the LLM.
    """
    entry = {
        'timestamp':       datetime.now().isoformat(),
        'query':           query,
        'query_type':      qtype,
        'chunks_used':     chunks_used,
        'top_similarity':  round(sim_scores[0], 4) if sim_scores else 0,
        'avg_similarity':  round(sum(sim_scores) / len(sim_scores), 4) if sim_scores else 0,
        'response_length': len(response),
    }

    existing_logs = _read_log()
    existing_logs.append(entry)
    _write_log(existing_logs)


def _read_log() -> List[dict]:
    """Read all existing log entries from the JSON file.

    Returns an empty list if the file does not exist or is corrupted,
    so a bad log file never crashes the pipeline.

    Returns:
        List of log entry dicts, or [] if the file is missing or unreadable.
    """
    if not os.path.exists(LOG_FILE):
        return []

    try:
        with open(LOG_FILE, 'r', encoding='utf-8') as log_file:
            return json.load(log_file)
    except (json.JSONDecodeError, OSError) as error:
        # Log file is corrupted or unreadable — start fresh rather than crash
        logger.warning("Could not read log file '%s': %s — starting with empty log.", LOG_FILE, error)
        return []


def _write_log(entries: List[dict]) -> None:
    """Write all log entries back to the JSON file with pretty indentation.

    Args:
        entries: The complete list of log entry dicts to write.
    """
    try:
        with open(LOG_FILE, 'w', encoding='utf-8') as log_file:
            json.dump(entries, log_file, indent=2)
    except OSError as error:
        logger.error("Could not write log file '%s': %s", LOG_FILE, error)
