"""metrics.py — Stateless RAG evaluation scoring functions.

WHY THIS FILE EXISTS:
    Keeping scoring functions separate from the Benchmarker class makes each
    metric independently testable and reusable. None of these functions hold
    any state — they take plain Python values in and return a float out.

SCORING CONVENTIONS:
    All functions return a float in [0.0, 1.0] unless documented otherwise.
    0.0 = worst possible score.  1.0 = best possible score.

LLM-AS-JUDGE FUNCTIONS:
    score_faithfulness_llm and score_answer_relevancy_llm call the local
    Ollama language model to grade answer quality. They are more reliable than
    word-overlap alone but add one extra LLM call per question per metric.
"""

from typing import List

import ollama

__all__ = [
    'score_faithfulness_llm',
    'score_answer_relevancy_llm',
    'score_ground_truth_match',
    'score_keyword_recall',
    'score_context_relevance',
    'score_precision_at_k',
    'score_mrr',
]

# Words excluded from all lexical overlap metrics — they carry no semantic content.
# Used by score_ground_truth_match to focus on meaningful words only.
_STOPWORDS: set = {
    'a', 'an', 'the', 'is', 'are', 'was', 'were', 'do', 'does', 'it', 'its',
    'to', 'of', 'in', 'for', 'and', 'or', 'not', 'with', 'on', 'at', 'by',
    'this', 'that', 'be', 'as', 'i', 'you', 'we', 'they', 'but', 'so', 'if',
}


def score_faithfulness_llm(
    question: str,
    response: str,
    context: str,
    model: str,
) -> float:
    """Ask the language model to grade whether the answer stays grounded in the context.

    Uses a 1–5 rating scale, then normalises to [0.0, 1.0].
    1 = the answer invents facts not present in the context (hallucination).
    5 = every claim in the answer comes directly from the retrieved context.

    Falls back to 0.5 (neutral) if the model returns an unparseable response.

    Args:
        question: The original question the user asked.
        response: The answer generated by the RAG pipeline.
        context:  The retrieved chunks joined into a single block of text.
        model:    The Ollama model name to use as the judge.

    Returns:
        Float in [0.0, 1.0]. Higher is better.
    """
    prompt = (
        "You are a strict factual evaluator. Rate how faithfully this answer "
        "is grounded in the provided context. Do NOT reward the answer for "
        "general knowledge — only reward it for staying within the given context.\n\n"
        f"Context:\n{context}\n\n"
        f"Question: {question}\n"
        f"Answer: {response}\n\n"
        "Rating scale:\n"
        "1 = Answer contains significant information NOT in the context (hallucination)\n"
        "2 = Answer mostly hallucinates with only some grounding\n"
        "3 = Answer is partially grounded — some claims from context, some invented\n"
        "4 = Answer is mostly grounded with only minor additions beyond the context\n"
        "5 = Every claim in the answer comes directly from the context\n\n"
        "Respond with ONLY a single digit (1, 2, 3, 4, or 5). No explanation."
    )
    try:
        result = ollama.chat(
            model=model,
            messages=[{'role': 'user', 'content': prompt}],
        )
        text = result['message']['content'].strip()
        # Extract the first valid rating digit from the response
        for char in text:
            if char in '12345':
                # Normalise: 1 → 0.00, 2 → 0.25, 3 → 0.50, 4 → 0.75, 5 → 1.00
                return (int(char) - 1) / 4.0
    except Exception:
        pass  # any Ollama error falls through to the neutral fallback
    return 0.5


def score_answer_relevancy_llm(
    question: str,
    response: str,
    model: str,
) -> float:
    """Ask the language model to grade whether the answer actually addresses the question.

    Uses a 1–5 rating scale, then normalises to [0.0, 1.0].
    1 = answer ignores the question entirely.
    5 = answer completely and directly addresses the question.

    Falls back to 0.5 if the model returns an unparseable response.

    Args:
        question: The original question the user asked.
        response: The answer generated by the RAG pipeline.
        model:    The Ollama model name to use as the judge.

    Returns:
        Float in [0.0, 1.0]. Higher is better.
    """
    prompt = (
        "You are a strict evaluator. Rate how well this answer addresses the question.\n\n"
        f"Question: {question}\n"
        f"Answer: {response}\n\n"
        "Rating scale:\n"
        "1 = The answer does not address the question at all\n"
        "2 = The answer barely addresses the question\n"
        "3 = The answer partially addresses the question\n"
        "4 = The answer mostly addresses the question with minor gaps\n"
        "5 = The answer completely and directly addresses the question\n\n"
        "Respond with ONLY a single digit (1, 2, 3, 4, or 5). No explanation."
    )
    try:
        result = ollama.chat(
            model=model,
            messages=[{'role': 'user', 'content': prompt}],
        )
        text = result['message']['content'].strip()
        for char in text:
            if char in '12345':
                return (int(char) - 1) / 4.0
    except Exception:
        pass
    return 0.5


def score_ground_truth_match(response: str, ground_truth: str) -> float:
    """Measure how closely the response matches the known correct answer using F1 word overlap.

    This is a lexical (word-matching) metric. It rewards responses that use the same
    words as the ground truth. It does not measure semantic meaning — use alongside
    the LLM-as-judge metrics for a complete picture.

    Args:
        response:     The answer generated by the RAG pipeline.
        ground_truth: The expected correct answer text.

    Returns:
        Float in [0.0, 1.0]. 1.0 = perfect word overlap with the ground truth.
    """
    # Strip common words that add noise — keep only meaningful content words
    ground_truth_words = set(ground_truth.lower().split()) - _STOPWORDS
    response_words     = set(response.lower().split())     - _STOPWORDS

    if not ground_truth_words or not response_words:
        return 0.0

    intersection = ground_truth_words & response_words

    # Precision: of the words the response used, how many were in the ground truth?
    precision = len(intersection) / len(response_words)

    # Recall: of the ground truth words, how many appeared in the response?
    recall = len(intersection) / len(ground_truth_words)

    if precision + recall == 0:
        return 0.0

    # F1 balances precision (staying on topic) and recall (covering key points)
    return min(2 * precision * recall / (precision + recall), 1.0)


def score_keyword_recall(response: str, keywords: List[str]) -> float:
    """Fraction of expected keywords found anywhere in the response (case-insensitive).

    If no keywords are provided, returns 1.0 — vacuously perfect since
    there is nothing to check.

    Args:
        response: The answer generated by the RAG pipeline.
        keywords: Strings expected to appear in a correct answer (e.g. ['sleep', '16']).

    Returns:
        Float in [0.0, 1.0]. 1.0 = all expected keywords found.
    """
    if not keywords:
        return 1.0
    response_lower = response.lower()
    found = sum(1 for kw in keywords if kw.lower() in response_lower)
    return found / len(keywords)


def score_context_relevance(reranked: list, top_n: int) -> float:
    """Mean cosine similarity of the top-N reranked chunks.

    Measures retrieval quality independently of the language model — a high score
    means the system found document chunks that were mathematically similar to
    the query, regardless of whether the LLM used them well.

    Args:
        reranked: List of (entry_dict, similarity_score, rerank_score) tuples
                  as returned by VectorStore._rerank().
        top_n:    How many of the top chunks to include in the mean.

    Returns:
        Float in [0.0, 1.0].
    """
    if not reranked:
        return 0.0
    # The similarity score is the second element in each tuple
    scores = [similarity for _, similarity, _ in reranked[:top_n]]
    return sum(scores) / len(scores) if scores else 0.0


def score_precision_at_k(reranked: list, keywords: List[str], k: int = 5) -> float:
    """Fraction of the top-K retrieved chunks that contain at least one expected keyword.

    Measures retrieval precision — did the system actually fetch the chunks that
    contain the information needed to answer the question?

    A chunk is counted as "relevant" if it contains at least one of the expected
    keywords (case-insensitive substring match).

    Args:
        reranked: List of (entry_dict, similarity_score, rerank_score) tuples.
        keywords: Keywords that indicate a chunk is relevant (e.g. ['sleep', '16']).
        k:        How many top chunks to evaluate (default 5).

    Returns:
        Float in [0.0, 1.0]. 1.0 = all top-K chunks contained at least one keyword.
    """
    if not keywords or not reranked:
        return 0.0
    top_k = reranked[:k]
    relevant = sum(
        1 for entry, _, _ in top_k
        if any(kw.lower() in entry['text'].lower() for kw in keywords)
    )
    return relevant / len(top_k)


def score_mrr(reranked: list, keywords: List[str]) -> float:
    """Mean Reciprocal Rank — how high up the list was the first relevant chunk?

    MRR = 1 / rank_of_first_relevant_chunk.

    Examples:
        First chunk is relevant  → MRR = 1/1 = 1.00 (best)
        Second chunk is relevant → MRR = 1/2 = 0.50
        Third chunk is relevant  → MRR = 1/3 = 0.33
        No relevant chunk found  → MRR = 0.00 (worst)

    Args:
        reranked: List of (entry_dict, similarity_score, rerank_score) tuples.
        keywords: Keywords that mark a chunk as relevant to the question.

    Returns:
        Float in [0.0, 1.0].
    """
    if not keywords or not reranked:
        return 0.0
    for rank, (entry, _, _) in enumerate(reranked, start=1):
        if any(kw.lower() in entry['text'].lower() for kw in keywords):
            return 1.0 / rank
    return 0.0  # no relevant chunk found anywhere in the reranked list
